AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Voice Planner Alexa Skill Lambda Function

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs22.x
    Environment:
      Variables:
        SUPABASE_URL: !Ref SupabaseUrl
        SUPABASE_SERVICE_KEY: !Ref SupabaseServiceKey
        DISABLE_LICENSE_VALIDATION: 'true'

Parameters:
  SupabaseUrl:
    Type: String
    Description: Supabase project URL
    NoEcho: true
  SupabaseServiceKey:
    Type: String
    Description: Supabase service role key
    NoEcho: true
  AlexaSkillId:
    Type: String
    Description: Alexa Skill ID

Resources:
  NotionAssistantFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: dist/index.handler
      Policies:
        - CloudWatchLogsFullAccess
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
          Properties:
            SkillId: !Ref AlexaSkillId

Outputs:
  NotionAssistantFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt NotionAssistantFunction.Arn

